baseURL = 'http://rixkft.hu/'
languageCode = 'en-us'
title = 'RIX Kft.'
theme = 'hugo-coder'
enableEmoji = true

[params]
author = "RIX Kft."
description = "Automation done right"
keywords = "software,development,automation,iot"
info = ["Automation", "Software Development"]
since = 1992
rtl = false
colorScheme = "auto"
