baseURL = 'http://rixkft.hu/'
languageCode = 'en-us'
title = 'RIX Kft.'
theme = 'rix'
enableEmoji = true

[params]
author = "RIX Kft."
description = "Automation done right"
keywords = "software,development,automation,iot"
info = ["Automation", "Software Development"]
since = 1992
rtl = false
colorScheme = "auto"

defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true

[languages]
[languages.hu]
contentDir = 'content/hu'
disabled = false
languageCode = 'hu-HU'
languageDirection = 'ltr'
languageName = 'Magyar'
title = 'RIX Kft.'
weight = 2
[languages.en]
contentDir = 'content/en'
disabled = false
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
title = 'RIX Kft.'
weight = 1

[params.goatCounter]
code = "rixkft"
